# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-13 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='coreDataID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
