# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-14 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_sequences_workout_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EM_Containers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreDataID', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sequences',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='database.Workouts'),
        ),
        migrations.AddField(
            model_name='em_containers',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_containers', to='database.Sequences'),
        ),
    ]
