# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-14 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20180314_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreDataID', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('variation', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
