# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180316_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_metrics',
            name='set_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
