# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-20 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_exercise_metrics_coredataid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_metrics',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise_metrics',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise_metrics',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise_metrics',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise_metrics',
            name='velocity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise_metrics',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
