# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20180320_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_metrics',
            name='personalRecords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Exercises'),
        ),
    ]
