# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-21 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_exercise_metrics_personalrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='oneRepMax',
            field=models.IntegerField(default=0),
        ),
    ]
