# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20180321_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreDataID', models.IntegerField()),
            ],
        ),
    ]
