# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-22 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_auto_20180322_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric_info',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='database.Exercises'),
            preserve_default=False,
        ),
    ]
